apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: <student-id>-strimzi-mm2
  namespace: event-automation
spec:
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 3
          emit.checkpoints.enabled: true  
          refresh.groups.interval.seconds: 60  
          sync.group.offsets.enabled: true  
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      sourceConnector:
        config:
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          sync.topic.acls.enabled: 'false'
      sourceCluster: <student-id>-source
      targetCluster: <student-id>-target
      topicsPattern: strimzi-topic1
      groupsPattern: .*
  clusters:
    - alias: <student-id>-source
      bootstrapServers: 'rajcluster-tok05-b3c-16x6-992844b4e64c83c3dbd5e7b5e2da5328-0000.jp-tok.containers.appdomain.cloud:31496'
    - config:
        config.storage.replication.factor: 3
        offset.storage.replication.factor: 3
        status.storage.replication.factor: 3
      alias: <student-id>-target
      bootstrapServers: 'my-kafka-cluster-ibm-es-kp-bootstrap.event-automation.svc:9095'
      authentication:
        passwordSecret:
          password: password
          secretName: es-admin
        type: scram-sha-512
        username: es-admin
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: my-kafka-cluster-cluster-ca-cert
  template:
    pod:
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 11.2.1
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: <student-id>-strimzi-mm2-mirrormaker2
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          productCloudpakRatio: '2:1'
  connectCluster: <student-id>-target
  replicas: 1
